"""Generated from pyproject.toml by scripts/generate_release_identity.py."""

# Do not edit this file by hand. Change [project].version and regenerate.
APPLICATION_VERSION = "0.2.1a1"
RELEASE_CHANNEL = "alpha"
RELEASE_STAGE = "alpha.1"
DISPLAY_NAME = "Vesta 0.2.1 Alpha.1"
PUBLISHED_TAG = "v0.2.1a1"
