#!/usr/bin/env python3
"""Generate all lifecycle projections from the versioned JSON source."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import pprint
from typing import Any, Mapping, Sequence


ROOT = Path(__file__).resolve().parents[1]
SCHEMA_PATH = ROOT / "opaihub" / "lifecycle_schema.json"
GENERATED_NOTICE = (
    "Generated by scripts/generate_lifecycle.py from "
    "opaihub/lifecycle_schema.json. DO NOT EDIT."
)


def load_schema(path: Path) -> dict[str, Any]:
    schema = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(schema, dict):
        raise ValueError("lifecycle schema must be a JSON object")
    _validate_schema(schema)
    return schema


def _validate_schema(schema: Mapping[str, Any]) -> None:
    version = schema.get("schema_version")
    if isinstance(version, bool) or not isinstance(version, int) or version < 1:
        raise ValueError("schema_version must be a positive integer")

    states = schema.get("states")
    if not isinstance(states, list) or not states:
        raise ValueError("states must be a non-empty list")
    state_ids = [state.get("id") for state in states if isinstance(state, dict)]
    if len(state_ids) != len(states) or any(
        not isinstance(item, str) for item in state_ids
    ):
        raise ValueError("every state requires a string id")
    if len(state_ids) != len(set(state_ids)):
        raise ValueError("state ids must be unique")
    by_state = {state["id"]: state for state in states}

    if by_state.get("cancel_requested", {}).get("terminal") is not False:
        raise ValueError("cancel_requested must be non-terminal")
    cancelled = by_state.get("cancelled", {})
    if (
        cancelled.get("terminal") is not True
        or cancelled.get("requires_reconciliation") is not True
    ):
        raise ValueError("cancelled must be terminal and require reconciliation")

    for state in states:
        required = {
            "classification",
            "terminal",
            "cancellation_eligible",
            "requires_reconciliation",
            "exit_code",
            "presentation_category",
            "label",
        }
        missing = required - state.keys()
        if missing:
            raise ValueError(f"state {state['id']} is missing {sorted(missing)}")
        if state["terminal"] and not isinstance(state["exit_code"], int):
            raise ValueError(f"terminal state {state['id']} requires an exit code")
        if not state["terminal"] and state["exit_code"] is not None:
            raise ValueError(
                f"non-terminal state {state['id']} cannot have an exit code"
            )

    reasons = schema.get("reason_classes")
    if not isinstance(reasons, list) or not reasons:
        raise ValueError("reason_classes must be a non-empty list")
    reason_ids = {reason.get("id") for reason in reasons if isinstance(reason, dict)}
    if len(reason_ids) != len(reasons) or None in reason_ids:
        raise ValueError("reason class ids must be unique strings")

    edges: set[tuple[str, str]] = set()
    for rule in schema.get("transitions", []):
        if not isinstance(rule, dict):
            raise ValueError("transition rules must be objects")
        source = rule.get("from")
        targets = rule.get("to")
        if source not in by_state or not isinstance(targets, list) or not targets:
            raise ValueError("transition rules require known source and targets")
        if by_state[source]["terminal"]:
            raise ValueError(
                f"terminal state {source} cannot have outgoing transitions"
            )
        if rule.get("reason") not in reason_ids:
            raise ValueError(f"transition from {source} has an unknown reason class")
        if not isinstance(rule.get("creates_new_attempt"), bool):
            raise ValueError("transition creates_new_attempt must be boolean")
        if not isinstance(rule.get("cancellation_eligible"), bool):
            raise ValueError("transition cancellation_eligible must be boolean")
        guards = rule.get("guards")
        if (
            not isinstance(guards, dict)
            or not {"verification", "delivery"} <= guards.keys()
        ):
            raise ValueError(
                "every transition requires verification and delivery guards"
            )
        for target in targets:
            if target not in by_state:
                raise ValueError(f"transition targets unknown state {target}")
            edge = (source, target)
            if edge in edges:
                raise ValueError(f"duplicate transition {source} -> {target}")
            edges.add(edge)

    repair = _expanded_transitions(schema)
    repair = [
        item
        for item in repair
        if item["from"] == "verifying" and item["to"] == "running"
    ]
    if len(repair) != 1 or repair[0]["reason"] != "verification_repair":
        raise ValueError("verifying -> running must use verification_repair")

    mappings = schema.get("legacy_mappings")
    unknown = mappings.get("unknown") if isinstance(mappings, dict) else None
    if not isinstance(unknown, dict) or unknown.get("state") != "needs_attention":
        raise ValueError("unknown legacy data must degrade to needs_attention")
    if (
        unknown.get("compatibility") != "incompatible"
        or unknown.get("automatic_retry") is not False
    ):
        raise ValueError("unknown legacy data must be incompatible and non-retryable")
    degraded_inputs = schema.get("degraded_inputs")
    required_degradations = {
        "unknown_schema_version",
        "unknown_state",
        "unknown_status",
    }
    if (
        not isinstance(degraded_inputs, dict)
        or set(degraded_inputs) != required_degradations
    ):
        raise ValueError("schema, state, and status degradation rules are required")
    for input_class, rule in degraded_inputs.items():
        if rule != {
            "state": "needs_attention",
            "compatibility": "incompatible",
            "automatic_retry": False,
        }:
            raise ValueError(
                f"{input_class} must degrade incompatibly to needs_attention"
            )

    _validate_background_compatibility(
        schema, state_ids=set(state_ids), by_state=by_state
    )


def _validate_background_compatibility(
    schema: Mapping[str, Any], *, state_ids: set[str], by_state: Mapping[str, Any]
) -> None:
    """#612: the background status projection must be total and consistent.

    This is the check that makes the PR #668 crash class impossible rather
    than merely fixed: ``needs_attention`` was missing from the (then
    hand-maintained) map, and the omission surfaced as a ``KeyError`` on a
    background worker thread at runtime. Requiring totality here turns the
    same mistake into a generation-time failure that CI's ``--check`` gate
    blocks before it can merge.
    """

    compat = schema.get("background_compatibility")
    if not isinstance(compat, dict):
        raise ValueError("background_compatibility section is required")

    statuses = compat.get("statuses")
    if not isinstance(statuses, dict) or not statuses:
        raise ValueError("background_compatibility.statuses must be a non-empty object")
    for word, spec in statuses.items():
        if not isinstance(spec, dict):
            raise ValueError(f"background status {word!r} must be an object")
        if not isinstance(spec.get("terminal"), bool):
            raise ValueError(f"background status {word!r} needs a boolean terminal")
        target = spec.get("state")
        if target not in state_ids:
            raise ValueError(
                f"background status {word!r} maps to unknown state {target!r}"
            )
        # A compatibility word may collapse onto a canonical state (e.g.
        # "interrupted" -> failed), but it must agree about terminality:
        # a word claiming to be terminal cannot resolve to a live state.
        if spec["terminal"] != bool(by_state[target]["terminal"]):
            raise ValueError(
                f"background status {word!r} disagrees with {target!r} about terminality"
            )
        if (
            not isinstance(spec.get("default_reason"), str)
            or not spec["default_reason"]
        ):
            raise ValueError(f"background status {word!r} needs a default_reason")

    forward = compat.get("state_to_status")
    if not isinstance(forward, dict):
        raise ValueError("background_compatibility.state_to_status must be an object")
    missing = sorted(state_ids - set(forward))
    if missing:
        raise ValueError(
            "background_compatibility.state_to_status must cover every state; "
            f"missing: {', '.join(missing)}"
        )
    unknown_states = sorted(set(forward) - state_ids)
    if unknown_states:
        raise ValueError(
            f"state_to_status maps unknown states: {', '.join(unknown_states)}"
        )
    for state_id, word in forward.items():
        if word not in statuses:
            raise ValueError(
                f"state {state_id!r} maps to unknown background status {word!r}"
            )
        # A terminal state must never project to a word older readers treat
        # as still-running, and vice versa — that is how a finished run gets
        # reported as in-flight (or a live one as finished) to the pre-#379
        # automation CLI.
        if bool(by_state[state_id]["terminal"]) != bool(statuses[word]["terminal"]):
            raise ValueError(
                f"state {state_id!r} is terminal={by_state[state_id]['terminal']} but "
                f"projects to background status {word!r} with "
                f"terminal={statuses[word]['terminal']}"
            )

    fallback = compat.get("fallback_status")
    if fallback not in statuses:
        raise ValueError(
            "background_compatibility.fallback_status must be a known status"
        )


def _expanded_transitions(schema: Mapping[str, Any]) -> list[dict[str, Any]]:
    transitions: list[dict[str, Any]] = []
    for rule in schema["transitions"]:
        for target in rule["to"]:
            transitions.append(
                {
                    "from": rule["from"],
                    "to": target,
                    "reason": rule["reason"],
                    "creates_new_attempt": rule["creates_new_attempt"],
                    "cancellation_eligible": rule["cancellation_eligible"],
                    "guards": dict(rule["guards"]),
                }
            )
    return transitions


def _python_literal(value: Any) -> str:
    return pprint.pformat(value, width=88, sort_dicts=True)


def _render_python(schema: Mapping[str, Any], transitions: list[dict[str, Any]]) -> str:
    states = schema["states"]
    state_ids = tuple(state["id"] for state in states)
    terminals = tuple(state["id"] for state in states if state["terminal"])
    state_specs = {state["id"]: dict(state) for state in states}
    exit_codes = {
        state["id"]: state["exit_code"] for state in states if state["terminal"]
    }
    legacy = schema["legacy_mappings"]
    compat = schema["background_compatibility"]
    background_statuses = tuple(sorted(compat["statuses"]))
    background_terminal = tuple(
        sorted(word for word, spec in compat["statuses"].items() if spec["terminal"])
    )
    background_state_for_status = {
        word: spec["state"] for word, spec in sorted(compat["statuses"].items())
    }
    background_reason_for_status = {
        word: spec["default_reason"]
        for word, spec in sorted(compat["statuses"].items())
    }
    return f'''# {GENERATED_NOTICE}
"""Canonical lifecycle data generated at build time."""

from __future__ import annotations

from typing import Any


SCHEMA_VERSION = {schema["schema_version"]}
ACCEPTED_LEGACY_SCHEMA_VERSIONS: tuple[int, ...] = {_python_literal(tuple(schema["accepted_legacy_schema_versions"]))}
STATE_IDS: tuple[str, ...] = {_python_literal(state_ids)}
TERMINAL_STATE_IDS: frozenset[str] = frozenset({_python_literal(terminals)})
STATE_SPECS: dict[str, dict[str, Any]] = {_python_literal(state_specs)}
TRANSITIONS: tuple[dict[str, Any], ...] = tuple({_python_literal(transitions)})
EXIT_CODES: dict[str, int] = {_python_literal(exit_codes)}
REASON_CLASSES: dict[str, dict[str, Any]] = {_python_literal({item["id"]: dict(item) for item in schema["reason_classes"]})}
LEGACY_STATE_MAP: dict[str, str] = {_python_literal(legacy["states"])}
LEGACY_STATUS_MAP: dict[str, str] = {_python_literal(legacy["statuses"])}
UNKNOWN_COMPATIBILITY: dict[str, Any] = {_python_literal(legacy["unknown"])}
DEGRADED_INPUTS: dict[str, dict[str, Any]] = {_python_literal(schema["degraded_inputs"])}

# #612: the pre-#379 background-automation status vocabulary, generated so it
# can no longer drift behind RunState (PR #668's worker-thread crash).
# BACKGROUND_STATUS_FOR_STATE is validated TOTAL over STATE_IDS at generation
# time, so a new state without a mapping fails the build, not a live run.
BACKGROUND_STATUSES: frozenset[str] = frozenset({_python_literal(background_statuses)})
BACKGROUND_TERMINAL_STATUSES: frozenset[str] = frozenset({_python_literal(background_terminal)})
BACKGROUND_STATUS_FOR_STATE: dict[str, str] = {_python_literal(dict(sorted(compat["state_to_status"].items())))}
BACKGROUND_STATE_FOR_STATUS: dict[str, str] = {_python_literal(background_state_for_status)}
BACKGROUND_REASON_FOR_STATUS: dict[str, str] = {_python_literal(background_reason_for_status)}
BACKGROUND_FALLBACK_STATUS = {compat["fallback_status"]!r}

_TRANSITION_BY_EDGE = {{
    (spec["from"], spec["to"]): spec for spec in TRANSITIONS
}}


def transition_spec(from_state: str, to_state: str) -> dict[str, Any] | None:
    """Return metadata for a legal edge, or ``None`` for an illegal edge."""

    return _TRANSITION_BY_EDGE.get((from_state, to_state))
'''


def _json_text(value: Any, *, indent: int = 2) -> str:
    return json.dumps(value, indent=indent, sort_keys=True, ensure_ascii=False) + "\n"


def _render_browser(
    schema: Mapping[str, Any], transitions: list[dict[str, Any]]
) -> str:
    states = schema["states"]
    payload = {
        "schemaVersion": schema["schema_version"],
        "acceptedLegacySchemaVersions": schema["accepted_legacy_schema_versions"],
        "stateIds": [state["id"] for state in states],
        "terminalStateIds": [state["id"] for state in states if state["terminal"]],
        "stateSpecs": {state["id"]: state for state in states},
        "transitions": transitions,
        "exitCodes": {
            state["id"]: state["exit_code"] for state in states if state["terminal"]
        },
        "reasonClasses": {item["id"]: item for item in schema["reason_classes"]},
        "legacyMappings": schema["legacy_mappings"],
        "degradedInputs": schema["degraded_inputs"],
    }
    encoded = json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=False)
    return f"""// {GENERATED_NOTICE}
(function (global) {{
  "use strict";

  var data = {encoded};
  var byEdge = Object.create(null);
  data.transitions.forEach(function (spec) {{
    Object.freeze(spec.guards);
    Object.freeze(spec);
    byEdge[spec.from + "\\u0000" + spec.to] = spec;
  }});

  data.acceptedLegacySchemaVersions = Object.freeze(data.acceptedLegacySchemaVersions);
  data.stateIds = Object.freeze(data.stateIds);
  data.terminalStateIds = Object.freeze(data.terminalStateIds);
  data.transitions = Object.freeze(data.transitions);
  data.transitionSpec = function (fromState, toState) {{
    return byEdge[fromState + "\\u0000" + toState] || null;
  }};
  data.canTransition = function (fromState, toState) {{
    return data.transitionSpec(fromState, toState) !== null;
  }};
  data.isTerminal = function (state) {{
    return data.terminalStateIds.indexOf(state) !== -1;
  }};
  global.OPaiLifecycle = Object.freeze(data);
}})(typeof window !== "undefined" ? window : globalThis);
"""


def _render_fixture(
    schema: Mapping[str, Any], transitions: list[dict[str, Any]]
) -> str:
    terminal_states = sorted(
        state["id"] for state in schema["states"] if state["terminal"]
    )
    fixture = {
        "_generated": GENERATED_NOTICE,
        "schema_version": schema["schema_version"],
        "terminal_states": terminal_states,
        "vectors": [
            {"from": item["from"], "to": item["to"], "reason": item["reason"]}
            for item in transitions
        ],
        "transition_specs": transitions,
        "exit_codes": {
            state["id"]: state["exit_code"]
            for state in schema["states"]
            if state["terminal"]
        },
        "legacy_mappings": schema["legacy_mappings"],
        "degraded_inputs": schema["degraded_inputs"],
        # #612: the background-automation projection travels with the other
        # golden vectors so any consumer (Python today, another surface
        # later) is checked against the same source of truth.
        "background_compatibility": schema["background_compatibility"],
    }
    return _json_text(fixture)


def _render_markdown(
    schema: Mapping[str, Any], transitions: list[dict[str, Any]]
) -> str:
    lines = [
        f"<!-- {GENERATED_NOTICE} -->",
        "# Canonical lifecycle schema",
        "",
        f"Schema version: **{schema['schema_version']}**.",
        "",
        "Stable IDs, reason classes, and the schema version are persisted meanings. Labels are presentation only.",
        "",
        "## States",
        "",
        "| State | Classification | Terminal | Cancel eligible | Reconciliation | Exit | Presentation |",
        "| --- | --- | --- | --- | --- | ---: | --- |",
    ]
    for state in schema["states"]:
        lines.append(
            "| {id} | {classification} | {terminal} | {cancel} | {reconcile} | {exit_code} | {presentation_category} |".format(
                id=state["id"],
                classification=state["classification"],
                terminal="yes" if state["terminal"] else "no",
                cancel="yes" if state["cancellation_eligible"] else "no",
                reconcile="required"
                if state["requires_reconciliation"]
                else "not required",
                exit_code=state["exit_code"] if state["exit_code"] is not None else "—",
                presentation_category=state["presentation_category"],
            )
        )
    lines.extend(
        [
            "",
            "`cancel_requested` is non-terminal. `cancelled` is terminal only after reconciliation.",
            "Unknown schema, state, or legacy status data degrades to terminal `needs_attention` with incompatible compatibility and no automatic retry.",
            "",
            "## Reason classes",
            "",
            "| Reason | Detail required | Meaning |",
            "| --- | --- | --- |",
        ]
    )
    for reason in schema["reason_classes"]:
        lines.append(
            f"| {reason['id']} | {'yes' if reason['requires_detail'] else 'no'} | {reason['description']} |"
        )
    lines.extend(
        [
            "",
            "## Legal transitions",
            "",
            "| From | To | Reason | New attempt | Cancel eligible | Verification guard | Delivery guard | Reconciliation guard |",
            "| --- | --- | --- | --- | --- | --- | --- | --- |",
        ]
    )
    for item in transitions:
        guards = item["guards"]
        lines.append(
            f"| {item['from']} | {item['to']} | {item['reason']} | "
            f"{'yes' if item['creates_new_attempt'] else 'no'} | "
            f"{'yes' if item['cancellation_eligible'] else 'no'} | "
            f"{guards['verification']} | {guards['delivery']} | {guards.get('reconciliation', 'not_required')} |"
        )
    lines.extend(
        [
            "",
            "Terminal states have no outgoing edges. The repair loop is `verifying -> running` with reason class `verification_repair` and does not create a new run attempt.",
            "",
            "## Legacy boundary mappings",
            "",
            "Legacy strings are input/output compatibility only. They never decide transitions, retry policy, or completion truth.",
            "",
            "| Kind | Legacy value | Canonical state |",
            "| --- | --- | --- |",
        ]
    )
    for kind in ("states", "statuses"):
        for legacy, canonical in sorted(schema["legacy_mappings"][kind].items()):
            lines.append(f"| {kind[:-1]} | {legacy} | {canonical} |")
    return "\n".join(lines) + "\n"


def render_all(schema: Mapping[str, Any]) -> dict[Path, str]:
    transitions = _expanded_transitions(schema)
    return {
        ROOT / "opaihub" / "generated_lifecycle.py": _render_python(
            schema, transitions
        ),
        ROOT / "opai" / "assets" / "web" / "generated-lifecycle.js": _render_browser(
            schema, transitions
        ),
        ROOT / "opaihub" / "data" / "lifecycle-fixtures.json": _render_fixture(
            schema, transitions
        ),
        ROOT / "docs" / "lifecycle-schema.md": _render_markdown(schema, transitions),
    }


def write_or_check(outputs: Mapping[Path, str], *, check: bool) -> bool:
    changed = False
    for path, content in outputs.items():
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if current == content:
            continue
        changed = True
        if check:
            print(f"stale generated lifecycle projection: {path.relative_to(ROOT)}")
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")
    return check and changed


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true", help="fail if projections are stale"
    )
    args = parser.parse_args(argv)
    outputs = render_all(load_schema(SCHEMA_PATH))
    return 1 if write_or_check(outputs, check=args.check) else 0


if __name__ == "__main__":
    raise SystemExit(main())
